# Usage:
    #   docker-compose up --force-recreate
    version: ‘2.1’
    services:
      #--------------#
      selenium:
        image: elgalu/selenium
      zalenium:
        image: dosel/zalenium
        container_name: zalenium
        hostname: zalenium
        tty: true
        volumes:
          - /tmp/videos:/home/seluser/videos
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 4444:4444
        command: >
          start --desiredContainers 2
                --maxDockerSeleniumContainers 2
                --videoRecordingEnabled true
        depends_on:
          - selenium